src/Plugins/Nop.Plugin.Shipping.UPS/Controllers/UPSShippingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Plugin.Shipping.UPS.Domain;
using Nop.Plugin.Shipping.UPS.Models;
using Nop.Plugin.Shipping.UPS.Services;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Shipping.UPS.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class UPSShippingController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IMeasureService _measureService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly UPSService _upsService;
        private readonly UPSSettings _upsSettings;

        #endregion

        #region Ctor

        public UPSShippingController(ILocalizationService localizationService,
            IMeasureService measureService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            UPSService upsService,
            UPSSettings upsSettings)
        {
            _localizationService = localizationService;
            _measureService = measureService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _upsService = upsService;
            _upsSettings = upsSettings;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            //whether user has the authority to manage configuration
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            //prepare common model
            var model = new UPSShippingModel
            {
                AccountNumber = _upsSettings.AccountNumber,
                AccessKey = _upsSettings.AccessKey,
                Username = _upsSettings.Username,
                Password = _upsSettings.Password,
                UseSandbox = _upsSettings.UseSandbox,
                AdditionalHandlingCharge = _upsSettings.AdditionalHandlingCharge,
                InsurePackage = _upsSettings.InsurePackage,
                CustomerClassification = (int)_upsSettings.CustomerClassification,
                PickupType = (int)_upsSettings.PickupType,
                PackagingType = (int)_upsSettings.PackagingType,
                SaturdayDeliveryEnabled = _upsSettings.SaturdayDeliveryEnabled,
                PassDimensions = _upsSettings.PassDimensions,
                PackingPackageVolume = _upsSettings.PackingPackageVolume,
                PackingType = (int)_upsSettings.PackingType,
                Tracing = _upsSettings.Tracing,
                WeightType = _upsSettings.WeightType,
                DimensionsType = _upsSettings.DimensionsType
            };

            //prepare offered delivery services
            var servicesCodes = _upsSettings.CarrierServicesOffered.Split(':', StringSplitOptions.RemoveEmptyEntries)
                .Select(idValue => idValue.Trim('[', ']')).ToList();

            //prepare available options
            model.AvailableCustomerClassifications = (await CustomerClassification.DailyRates.ToSelectListAsync(false))
                .Select(item => new SelectListItem(item.Text, item.Value)).ToList();
            model.AvailablePickupTypes = (await PickupType.DailyPickup.ToSelectListAsync(false))
                .Select(item => new SelectListItem(item.Text, item.Value)).ToList();
            model.AvailablePackagingTypes = (await PackagingType.CustomerSuppliedPackage.ToSelectListAsync(false))
                .Select(item => new SelectListItem(item.Text?.TrimStart('_'), item.Value)).ToList();
            model.AvaliablePackingTypes = (await PackingType.PackByDimensions.ToSelectListAsync(false))
                .Select(item => new SelectListItem(item.Text, item.Value)).ToList();
            model.AvailableCarrierServices = (await DeliveryService.Standard.ToSelectListAsync(false))
                .Select(item =>
            {
                var serviceCode = _upsService.GetUpsCode((DeliveryService)int.Parse(item.Value));
                return new SelectListItem($"UPS {item.Text?.TrimStart('_')}", serviceCode, servicesCodes.Contains(serviceCode));
            }).ToList();
            model.AvaliableWeightTypes = new List<SelectListItem> { new SelectListItem("LBS", "LBS"), new SelectListItem("KGS", "KGS") };
            model.AvaliableDimensionsTypes = new List<SelectListItem> { new SelectListItem("IN", "IN"), new SelectListItem("CM", "CM") };

            //check measures
            var weightSystemName = _upsSettings.WeightType switch { "LBS" => "lb", "KGS" => "kg", _ => null };
            if (await _measureService.GetMeasureWeightBySystemKeywordAsync(weightSystemName) == null)
                _notificationService.ErrorNotification($"Could not load '{weightSystemName}' <a href=\"{Url.Action("List", "Measure")}\" target=\"_blank\">measure weight</a>", false);

            var dimensionSystemName = _upsSettings.DimensionsType switch { "IN" => "inches", "CM" => "centimeters", _ => null };
            if (await _measureService.GetMeasureDimensionBySystemKeywordAsync(dimensionSystemName) == null)
                _notificationService.ErrorNotification($"Could not load '{dimensionSystemName}' <a href=\"{Url.Action("List", "Measure")}\" target=\"_blank\">measure dimension</a>", false);

            return View("~/Plugins/Shipping.UPS/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(UPSShippingModel model)
        {
            //whether user has the authority to manage configuration
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            //save settings
            _upsSettings.AccountNumber = model.AccountNumber;
            _upsSettings.AccessKey = model.AccessKey;
            _upsSettings.Username = model.Username;
            _upsSettings.Password = model.Password;
            _upsSettings.UseSandbox = model.UseSandbox;
            _upsSettings.AdditionalHandlingCharge = model.AdditionalHandlingCharge;
            _upsSettings.CustomerClassification = (CustomerClassification)model.CustomerClassification;
            _upsSettings.PickupType = (PickupType)model.PickupType;
            _upsSettings.PackagingType = (PackagingType)model.PackagingType;
            _upsSettings.InsurePackage = model.InsurePackage;
            _upsSettings.SaturdayDeliveryEnabled = model.SaturdayDeliveryEnabled;
            _upsSettings.PassDimensions = model.PassDimensions;
            _upsSettings.PackingPackageVolume = model.PackingPackageVolume;
            _upsSettings.PackingType = (PackingType)model.PackingType;
            _upsSettings.Tracing = model.Tracing;
            _upsSettings.WeightType = model.WeightType;
            _upsSettings.DimensionsType = model.DimensionsType;

            //use default services if no one is selected 
            if (!model.CarrierServices.Any())
            {
                model.CarrierServices = new List<string>
                {
                    _upsService.GetUpsCode(DeliveryService.Ground),
                    _upsService.GetUpsCode(DeliveryService.WorldwideExpedited),
                    _upsService.GetUpsCode(DeliveryService.Standard),
                    _upsService.GetUpsCode(DeliveryService._3DaySelect)
                };
            }
            _upsSettings.CarrierServicesOffered = string.Join(':', model.CarrierServices.Select(service => $"[{service}]"));

            await _settingService.SaveSettingAsync(_upsSettings);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        #endregion
    }
}

src/Plugins/Nop.Plugin.Shipping.UPS/Views/Configure.cshtml
@model UPSShippingModel

@using Nop.Plugin.Shipping.UPS.Domain
@using Nop.Plugin.Shipping.UPS.Models

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="UPSShipping" asp-action="Configure" method="post">
    <script>
        $(document).ready(function () {
            $("#PackingType").change(togglePackingType);
            togglePackingType();
        });

        function togglePackingType() {
            var selectedPackingTypeId = $("#PackingType").val();
            if (selectedPackingTypeId == @((int)PackingType.PackByDimensions)) {
                $('#pnlPassDimensions').showElement();
                $('#pnlPackingPackageVolume').hideElement();
            }
            else if (selectedPackingTypeId == @((int)PackingType.PackByOneItemPerPackage)) {
                $('#pnlPassDimensions').hideElement();
                $('#pnlPackingPackageVolume').hideElement();
            }
            else if (selectedPackingTypeId == @((int)PackingType.PackByVolume)) {
                $('#pnlPassDimensions').hideElement();
                $('#pnlPackingPackageVolume').showElement();
            }
        }
    </script>

    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AccountNumber" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AccountNumber" />
                        <span asp-validation-for="AccountNumber"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AccessKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AccessKey" />
                        <span asp-validation-for="AccessKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Username" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Username" />
                        <span asp-validation-for="Username"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Password" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="CustomerClassification" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="CustomerClassification" asp-items="Model.AvailableCustomerClassifications" />
                        <span asp-validation-for="CustomerClassification"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="PickupType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PickupType" asp-items="Model.AvailablePickupTypes" />
                        <span asp-validation-for="PickupType"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="PackagingType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PackagingType" asp-items="Model.AvailablePackagingTypes" />
                        <span asp-validation-for="PackagingType"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="InsurePackage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="InsurePackage" />
                        <span asp-validation-for="InsurePackage"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AdditionalHandlingCharge" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalHandlingCharge" />
                        <span asp-validation-for="AdditionalHandlingCharge"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AvailableCarrierServices" />
                    </div>
                    <div class="col-md-9">
                        @foreach (var service in Model.AvailableCarrierServices)
                        {
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" name="@(nameof(Model.CarrierServices))" value="@(service.Value)" checked="@(service.Selected)" />
                                    @(service.Text)
                                </label>
                            </div>
                        }
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="SaturdayDeliveryEnabled" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SaturdayDeliveryEnabled" />
                        <span asp-validation-for="SaturdayDeliveryEnabled"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="PackingType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PackingType" asp-items="Model.AvaliablePackingTypes" />
                        <span asp-validation-for="PackingType"></span>
                    </div>
                </div>
                <div class="form-group row" id="pnlPassDimensions">
                    <div class="col-md-3">
                        <nop-label asp-for="PassDimensions" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PassDimensions" />
                        <span asp-validation-for="PassDimensions"></span>
                    </div>
                </div>
                <div class="form-group row" id="pnlPackingPackageVolume">
                    <div class="col-md-3">
                        <nop-label asp-for="PackingPackageVolume" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PackingPackageVolume" />
                        <span asp-validation-for="PackingPackageVolume"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="WeightType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="WeightType" asp-items="Model.AvaliableWeightTypes" />
                        <span asp-validation-for="WeightType"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="DimensionsType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="DimensionsType" asp-items="Model.AvaliableDimensionsTypes" />
                        <span asp-validation-for="DimensionsType"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Tracing" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Tracing" />
                        <span asp-validation-for="Tracing"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>